route:
  receiver: 'tg-webhook'
  repeat_interval: 4h
  group_by: [ alertname ]


receivers:
  - name: 'tg-webhook'
    webhook_configs:
    - url: http://bot:8080/prom_alerts
      send_resolved: false
      
