{
 "title": "Acala/Karura",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "chain", "query": "acala,karura" },
   { "name": "time_period", "query": "15m,1h,3h,6h,12h,24h" },
   { "name": "account", "label": "account", "query": { "query": "label_values(account)" } }
  ]
 },
 "panels": [
  {
   "title": "Active Set Collators",
   "type": "table",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "acala_session_active_validators{chain=\"$chain\",account=~\"$account\"}",
     "legendFormat": "{{ account }}"
    }
   ]
  },
  {
   "title": "Current Session",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "acala_session_common{chain=\"$chain\", account=~\"$account\", name=\"current_session\"}",
     "legendFormat": "{{ account }}"
    }
   ]
  },
  {
   "title": "Active set collators count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "acala_session_common{chain=\"$chain\",name=\"active_validators_count\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Moonbeam collators points",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "acala_rewards_validator{chain=\"$chain\", account=~\"$account\"}",
     "legendFormat": "{{ account }}"
    }
   ]
  }
 ]
}