{
 "title": "Astar/Shiden",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "chain", "query": "astar,shiden" },
   { "name": "time_period", "query": "15m,1h,3h,6h,12h,24h" },
   { "name": "account", "label": "account", "query": { "query": "label_values(account)" } }
  ]
 },
 "panels": [
  {
   "title": "Active Set Collators",
   "type": "table",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "astar_activeCollators{chain=\"$chain\", account=~\"$account\"}",
     "legendFormat": "{{ account }}"
    }
   ]
  },
  {
   "title": "Current session",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "astar_currentSession{chain=\"$chain\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Collators points",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "astar_blockAuthorship{chain=\"$chain\", account=~\"$account\"}",
     "legendFormat": "{{ account }}"
    }
   ]
  },
  {
   "title": "Manta block authorship",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "astar_blockAuthorship{chain=\"$chain\"}\n",
     "legendFormat": "{{ account }}"
    }
   ]
  },
  {
   "title": "Session blocks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "astar_sessionBlocks{chain=\"$chain\"}",
     "legendFormat": "{{ account }}"
    }
   ]
  }
 ]
}