{
 "title": "P2P.ORG Avail dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "chain", "query": "turing,avail" },
   {
    "name": "account",
    "label": "account",
    "query": {
     "query": "label_values(avail_finality_prevotes{chain=\"$chain\"},account)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Era",
   "type": "stat",
   "description": "Current era. ",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(avail_staking_currentEra{chain=~\"$chain\"}[15s])"
    }
   ]
  },
  {
   "title": "Session(epoch)",
   "type": "stat",
   "description": "Session idx. ",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(avail_session_currentSession{chain=\"$chain\"}[15s])"
    }
   ]
  },
  {
   "title": "Total  points",
   "type": "stat",
   "description": "Total points.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(avail_staking_totalPoints{chain=\"$chain\"}[15s])"
    }
   ]
  },
  {
   "title": "Era progress percents",
   "type": "stat",
   "description": "Era progress.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(avail_staking_eraProgress{chain=\"$chain\"}[15s])"
    }
   ]
  },
  {
   "title": "Session progress percents",
   "type": "stat",
   "description": "Session progress.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(avail_session_sessionProgress{chain=\"$chain\"}[15s])"
    }
   ]
  },
  {
   "title": "Total validators",
   "type": "stat",
   "description": "Total validators. ",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(avail_session_validators{chain=\"$chain\"}[15s]))"
    }
   ]
  },
  {
   "title": "Total era points",
   "type": "timeseries",
   "description": "Total points yearned by whole network. ",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "avail_staking_totalPoints{chain=\"$chain\"}",
     "legendFormat": "{{ chain }}"
    }
   ]
  },
  { "title": "Finality", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "GRANPDA ratio",
   "type": "table",
   "description": "Finality ratio. ",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by (account) (max_over_time(avail_finality_precommits{chain=\"$chain\",account=~\"$account\"}[1m])) / on () group_left() max(max_over_time(avail_finality_roundsProcessed{chain=\"$chain\"}[1m])) * 100 and on(account) avail_session_validators == 1",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (account) (max_over_time(avail_finality_prevotes{chain=\"$chain\",account=~\"$account\"}[1m])) / on () group_left() max(max_over_time(avail_finality_roundsProcessed{chain=\"$chain\"}[1m])) * 100 and on(account) avail_session_validators == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block finality (prevotes)",
   "type": "timeseries",
   "description": "Prevotes",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "avail_finality_prevotes{chain=\"$chain\",account=~\"$account\"} > 0",
     "legendFormat": "{{ account }}"
    }
   ]
  },
  {
   "title": "Block finality (precommits)",
   "type": "timeseries",
   "description": "Precommits.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "avail_finality_precommits{chain=\"$chain\",account=~\"$account\"} > 0",
     "legendFormat": "{{ account }}"
    }
   ]
  },
  { "title": "Era validator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Earned points",
   "type": "stat",
   "description": "Earned points by selected validators.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(avail_staking_eraPoints{chain=\"$chain\",account=~\"$account\"}[30s]))"
    }
   ]
  },
  {
   "title": "Active validators",
   "type": "table",
   "description": "List of active validators.",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 53 },
   "targets": [
    {
     "expr": "max_over_time(avail_session_validators{chain=\"$chain\",account=~\"$account\"}[15s]) == 1",
     "legendFormat": "{{ validator }} - {{ account_addr }}"
    }
   ]
  },
  {
   "title": "Validators position chart",
   "type": "table",
   "description": "Select validators position chart.",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 53 },
   "targets": [
    {
     "expr": "max_over_time(avail_staking_validatorPositionChart{chain=\"$chain\",account=~\"$account\"}[15s]) + 1",
     "legendFormat": "{{ account }} "
    }
   ]
  },
  {
   "title": "Active validators",
   "type": "stat",
   "description": "Active selected validators.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(avail_session_validators{chain=\"$chain\",account=~\"$account\"}[15s]) > 0)"
    }
   ]
  },
  {
   "title": "Era points",
   "type": "graph",
   "description": "Selected validators era points.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avail_staking_eraPoints{chain=\"$chain\",account=~\"$account\"} > 0",
     "legendFormat": "{{ account }}"
    }
   ]
  }
 ]
}