{
 "title": "Polkadot/Kusama validator events",
 "tags": [ "Validators" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": {
     "query": "label_values(polkadot_events,chain)"
    }
   },
   {
    "name": "module",
    "query": {
     "query": "label_values(polkadot_events,module)"
    }
   },
   {
    "name": "method",
    "query": {
     "query": "label_values(polkadot_events{module=~\"$module\"},method)"
    }
   },
   {
    "name": "account",
    "label": "account",
    "query": {
     "query": "label_values(polkadot_events_by_account{chain=~\"$chain\"},account)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "events/sec",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "min by (module, method) (rate(polkadot_events{chain=\"$chain\",module=~\"$module\",method=~\"$method\"}[$__rate_interval])) > 0",
     "legendFormat": "{{module}}.{{method}}"
    }
   ]
  },
  { "title": "Events by account", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Events by validator account",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(polkadot_events_by_account{account=~\"$account\"}[$__rate_interval]) > 0",
     "legendFormat": "{{module}}.{{method}} {{account}}"
    }
   ]
  },
  {
   "title": "ParasDisputes initiators for valid candidates",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(polkadot_events_by_account{chain=\"$chain\",module=\"ParasDisputes\",method=\"DisputesConcluded\"}[$__rate_interval]) > 0",
     "legendFormat": "{{account}}"
    }
   ]
  },
  {
   "title": "Disruptions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(polkadot_events_by_account{chain=\"$chain\",module=\"ImOnline\",method=\"SomeOffline\"}[$__rate_interval]) > 0",
     "legendFormat": "seen offline {{account}}"
    },
    {
     "expr": "rate(polkadot_events_by_account{chain=\"$chain\",module=\"Staking\",method=\"SlashReported\"}[$__rate_interval]) > 0",
     "legendFormat": "slash reported {{account}}"
    }
   ]
  }
 ]
}