{
 "title": "Manta/Calamari",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "chain", "query": "manta,calamari" },
   { "name": "time_period", "query": "15m,1h,3h,6h,12h,24h" },
   { "name": "account", "label": "account", "query": { "query": "label_values(account)" } }
  ]
 },
 "panels": [
  {
   "title": "Active Set Collators",
   "type": "table",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "manta_activeCollators{chain=\"$chain\", account=~\"$account\"}",
     "legendFormat": "{{ account }}"
    }
   ]
  },
  {
   "title": "Current round",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "manta_currentRound{chain=\"$chain\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Median blocks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(manta_blocksMedian{chain=\"$chain\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 blocks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(manta_blocksP95{chain=\"$chain\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AVG blocks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(manta_blocksAvg{chain=\"$chain\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Manta collators points",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "manta_blockAuthorship{chain=\"$chain\", account=~\"$account\"}",
     "legendFormat": "{{ account }}"
    }
   ]
  },
  {
   "title": "Manta block authorship",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "manta_blockAuthorship{chain=\"$chain\"}\n",
     "legendFormat": "{{ account }}"
    }
   ]
  },
  {
   "title": "Round blocks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "manta_roundBlocks{chain=\"$chain\"}",
     "legendFormat": "{{ account }}"
    }
   ]
  }
 ]
}