{
 "title": "Moonbeam/Moonriver",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "chain", "query": "moonbeam,moonriver" },
   {
    "name": "Node",
    "query": {
     "query": "label_values(node_boot_time_seconds, job)"
    }
   },
   { "name": "time_period", "query": "15m,1h,3h,6h,12h,24h" }
  ]
 },
 "panels": [
  {
   "title": "Active Set Position",
   "type": "table",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (node) (moonbeam_activesetPosition{chain=\"$chain\",node=~\"$Node\"}[15s])",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Collators count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "moonbeam_activeCollatorsCount{chain=\"$chain\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current round",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "moonbeam_currentRound{chain=\"$chain\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ParaValidator epoch points",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by (node) (sum_over_time(moonbeam_blockAuthorship{chain=\"$chain\",node=~\"$Node\"}[$time_period])) / max(sum_over_time(moonbeam_blocksAvg{chain=\"$chain\"}[$time_period])) * 100 and on (node) moonbeam_activeCollators == 1",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (node) (sum_over_time(moonbeam_blockAuthorship{chain=\"$chain\",node=~\"$Node\"}[$time_period])) / max(sum_over_time(moonbeam_blocksMedian{chain=\"$chain\"}[$time_period])) * 100 and on (node) moonbeam_activeCollators == 1",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (node) (sum_over_time(moonbeam_blockAuthorship{chain=\"$chain\",node=~\"$Node\"}[$time_period])) / max(sum_over_time(moonbeam_blocksP95{chain=\"$chain\"}[$time_period])) * 100 and on (node) moonbeam_activeCollators == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 blocks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 14, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(moonbeam_blocksP95{chain=\"$chain\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Median blocks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 14, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(moonbeam_blocksMedian{chain=\"$chain\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AVG blocks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 14, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(moonbeam_blocksAvg{chain=\"$chain\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Moonbeam block authorship",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "moonbeam_blockAuthorship{chain=\"$chain\",node=~\"$Node\"} and on (account) moonbeam_activeCollators == 1",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Round blocks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "moonbeam_roundBlocks{chain=\"$chain\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  }
 ]
}